import type { Metadata } from "next";
import { Caveat, Handlee } from "next/font/google";
import "./globals.css";

export const caveat = Caveat({
	variable: "--font-caveat",
	subsets: ["latin"],
});

export const handlee = Handlee({
	variable: "--font-handlee",
	subsets: ["latin"],
	weight: ["400"],
});

export const metadata: Metadata = {
	title: "ToolsFlow",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.ico",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`back_gradient text-[var(--text-color-primary)]`}>
				{children}
			</body>
		</html>
	);
}
